# for local testing

services:

  postgresql-db:
    image: postgres:17.2
    # TODO move to .env file
    environment:
      - "POSTGRES_PASSWORD=test123"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=ctrchallenge"
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

  ab-test-lambda:
    build: .
    depends_on: 
      - postgresql-db
    ports:
      - "8080:8080"

  service-curl:
    build: ./curl-service
    depends_on:
      - ab-test-lambda