# for local testing

services:

  postgresql-db:
    image: postgres:17.2
    env_file: local.env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

  ab-test-lambda:
    build: .
    depends_on: 
      - postgresql-db
    env_file: local.env
    ports:
      - "8080:8080"

  service-curl:
    build: ./curl-service
    depends_on:
      - ab-test-lambda